name: resqnet_frontend
description: "ResQNet Emergency Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  country_picker: ^2.0.25
  file_picker: ^8.0.0
  geolocator: ^14.0.2
  geocoding: ^2.1.1   # 🔥 ADDED
  firebase_core: ^4.5.0
  firebase_messaging: ^16.1.2
  google_maps_flutter: ^2.6.0
  flutter_polyline_points: ^3.1.0
  path_provider: ^2.0.14
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/ambulance.png
    
flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon.png